# Generated by Django 3.1.1 on 2020-09-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
